// Generated by gencpp from file wheeltec_tracker_pkg/color.msg
// DO NOT EDIT!


#ifndef WHEELTEC_TRACKER_PKG_MESSAGE_COLOR_H
#define WHEELTEC_TRACKER_PKG_MESSAGE_COLOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheeltec_tracker_pkg
{
template <class ContainerAllocator>
struct color_
{
  typedef color_<ContainerAllocator> Type;

  color_()
    : angleX(0.0)
    , angleY(0.0)  {
    }
  color_(const ContainerAllocator& _alloc)
    : angleX(0.0)
    , angleY(0.0)  {
  (void)_alloc;
    }



   typedef float _angleX_type;
  _angleX_type angleX;

   typedef float _angleY_type;
  _angleY_type angleY;





  typedef boost::shared_ptr< ::wheeltec_tracker_pkg::color_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheeltec_tracker_pkg::color_<ContainerAllocator> const> ConstPtr;

}; // struct color_

typedef ::wheeltec_tracker_pkg::color_<std::allocator<void> > color;

typedef boost::shared_ptr< ::wheeltec_tracker_pkg::color > colorPtr;
typedef boost::shared_ptr< ::wheeltec_tracker_pkg::color const> colorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheeltec_tracker_pkg::color_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheeltec_tracker_pkg::color_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wheeltec_tracker_pkg::color_<ContainerAllocator1> & lhs, const ::wheeltec_tracker_pkg::color_<ContainerAllocator2> & rhs)
{
  return lhs.angleX == rhs.angleX &&
    lhs.angleY == rhs.angleY;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wheeltec_tracker_pkg::color_<ContainerAllocator1> & lhs, const ::wheeltec_tracker_pkg::color_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wheeltec_tracker_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wheeltec_tracker_pkg::color_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheeltec_tracker_pkg::color_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheeltec_tracker_pkg::color_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheeltec_tracker_pkg::color_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheeltec_tracker_pkg::color_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheeltec_tracker_pkg::color_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheeltec_tracker_pkg::color_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0889611e38ff06ce7765b61e0b0419be";
  }

  static const char* value(const ::wheeltec_tracker_pkg::color_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0889611e38ff06ceULL;
  static const uint64_t static_value2 = 0x7765b61e0b0419beULL;
};

template<class ContainerAllocator>
struct DataType< ::wheeltec_tracker_pkg::color_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheeltec_tracker_pkg/color";
  }

  static const char* value(const ::wheeltec_tracker_pkg::color_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheeltec_tracker_pkg::color_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angleX\n"
"float32 angleY\n"
;
  }

  static const char* value(const ::wheeltec_tracker_pkg::color_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheeltec_tracker_pkg::color_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angleX);
      stream.next(m.angleY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct color_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheeltec_tracker_pkg::color_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheeltec_tracker_pkg::color_<ContainerAllocator>& v)
  {
    s << indent << "angleX: ";
    Printer<float>::stream(s, indent + "  ", v.angleX);
    s << indent << "angleY: ";
    Printer<float>::stream(s, indent + "  ", v.angleY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELTEC_TRACKER_PKG_MESSAGE_COLOR_H
