// Generated by gencpp from file wheeltec_tracker_pkg/gesture.msg
// DO NOT EDIT!


#ifndef WHEELTEC_TRACKER_PKG_MESSAGE_GESTURE_H
#define WHEELTEC_TRACKER_PKG_MESSAGE_GESTURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheeltec_tracker_pkg
{
template <class ContainerAllocator>
struct gesture_
{
  typedef gesture_<ContainerAllocator> Type;

  gesture_()
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)
    , f(0.0)  {
    }
  gesture_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)
    , e(0.0)
    , f(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;

   typedef float _c_type;
  _c_type c;

   typedef float _d_type;
  _d_type d;

   typedef float _e_type;
  _e_type e;

   typedef float _f_type;
  _f_type f;





  typedef boost::shared_ptr< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> const> ConstPtr;

}; // struct gesture_

typedef ::wheeltec_tracker_pkg::gesture_<std::allocator<void> > gesture;

typedef boost::shared_ptr< ::wheeltec_tracker_pkg::gesture > gesturePtr;
typedef boost::shared_ptr< ::wheeltec_tracker_pkg::gesture const> gestureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wheeltec_tracker_pkg::gesture_<ContainerAllocator1> & lhs, const ::wheeltec_tracker_pkg::gesture_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.d == rhs.d &&
    lhs.e == rhs.e &&
    lhs.f == rhs.f;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wheeltec_tracker_pkg::gesture_<ContainerAllocator1> & lhs, const ::wheeltec_tracker_pkg::gesture_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wheeltec_tracker_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d0917f62e38c9b1c6fae9685fe09aa2";
  }

  static const char* value(const ::wheeltec_tracker_pkg::gesture_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d0917f62e38c9b1ULL;
  static const uint64_t static_value2 = 0xc6fae9685fe09aa2ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheeltec_tracker_pkg/gesture";
  }

  static const char* value(const ::wheeltec_tracker_pkg::gesture_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n"
"float32 b\n"
"float32 c\n"
"float32 d\n"
"float32 e\n"
"float32 f\n"
;
  }

  static const char* value(const ::wheeltec_tracker_pkg::gesture_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
      stream.next(m.e);
      stream.next(m.f);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gesture_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheeltec_tracker_pkg::gesture_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheeltec_tracker_pkg::gesture_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<float>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
    s << indent << "e: ";
    Printer<float>::stream(s, indent + "  ", v.e);
    s << indent << "f: ";
    Printer<float>::stream(s, indent + "  ", v.f);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEELTEC_TRACKER_PKG_MESSAGE_GESTURE_H
