(cl:defpackage yolo_new-msg
  (:use )
  (:export
   "<BOUNDINGBOX>"
   "BOUNDINGBOX"
   "<BOUNDINGBOXES>"
   "BOUNDINGBOXES"
   "<FLAG>"
   "FLAG"
   "<ARM_INIT_POSITION>"
   "ARM_INIT_POSITION"
   "<ARM_TARGET>"
   "ARM_TARGET"
   "<ARM_TARGET_POSITION>"
   "ARM_TARGET_POSITION"
   "<COLOR_IK_RESULT_NEW>"
   "COLOR_IK_RESULT_NEW"
   "<POSITION_COLOR>"
   "POSITION_COLOR"
  ))

