controller_list:
  - name: fake_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_hand_controller
    joints:
      - joint_6
      - joint_10
      - joint_7
      - joint_11
      - joint_8
      - joint_9
initial:  # Define initial robot poses.
  - group: arm
    pose: arm_home