// Generated by gencpp from file yolo_new/BoundingBox.msg
// DO NOT EDIT!


#ifndef YOLO_NEW_MESSAGE_BOUNDINGBOX_H
#define YOLO_NEW_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_new
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : probability(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , num(0)
    , distance(0.0)
    , Class()
    , xmid(0)
    , ymid(0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : probability(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , num(0)
    , distance(0.0)
    , Class(_alloc)
    , xmid(0)
    , ymid(0)  {
  (void)_alloc;
    }



   typedef double _probability_type;
  _probability_type probability;

   typedef int64_t _xmin_type;
  _xmin_type xmin;

   typedef int64_t _ymin_type;
  _ymin_type ymin;

   typedef int64_t _xmax_type;
  _xmax_type xmax;

   typedef int64_t _ymax_type;
  _ymax_type ymax;

   typedef int16_t _num_type;
  _num_type num;

   typedef double _distance_type;
  _distance_type distance;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Class_type;
  _Class_type Class;

   typedef int64_t _xmid_type;
  _xmid_type xmid;

   typedef int64_t _ymid_type;
  _ymid_type ymid;





  typedef boost::shared_ptr< ::yolo_new::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_new::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::yolo_new::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::yolo_new::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::yolo_new::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_new::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_new::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_new::BoundingBox_<ContainerAllocator1> & lhs, const ::yolo_new::BoundingBox_<ContainerAllocator2> & rhs)
{
  return lhs.probability == rhs.probability &&
    lhs.xmin == rhs.xmin &&
    lhs.ymin == rhs.ymin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymax == rhs.ymax &&
    lhs.num == rhs.num &&
    lhs.distance == rhs.distance &&
    lhs.Class == rhs.Class &&
    lhs.xmid == rhs.xmid &&
    lhs.ymid == rhs.ymid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_new::BoundingBox_<ContainerAllocator1> & lhs, const ::yolo_new::BoundingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_new

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_new::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_new::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_new::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_new::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_new::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_new::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_new::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5995e540d39f43ed6bd4cfe8b8af1f5e";
  }

  static const char* value(const ::yolo_new::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5995e540d39f43edULL;
  static const uint64_t static_value2 = 0x6bd4cfe8b8af1f5eULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_new::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_new/BoundingBox";
  }

  static const char* value(const ::yolo_new::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_new::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 probability\n"
"int64 xmin\n"
"int64 ymin\n"
"int64 xmax\n"
"int64 ymax\n"
"int16 num\n"
"float64 distance\n"
"string Class\n"
"int64 xmid\n"
"int64 ymid\n"
;
  }

  static const char* value(const ::yolo_new::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_new::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.probability);
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
      stream.next(m.num);
      stream.next(m.distance);
      stream.next(m.Class);
      stream.next(m.xmid);
      stream.next(m.ymid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_new::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_new::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "probability: ";
    Printer<double>::stream(s, indent + "  ", v.probability);
    s << indent << "xmin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymax);
    s << indent << "num: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Class);
    s << indent << "xmid: ";
    Printer<int64_t>::stream(s, indent + "  ", v.xmid);
    s << indent << "ymid: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ymid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_NEW_MESSAGE_BOUNDINGBOX_H
