// Generated by gencpp from file yolo_new/Flag.msg
// DO NOT EDIT!


#ifndef YOLO_NEW_MESSAGE_FLAG_H
#define YOLO_NEW_MESSAGE_FLAG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_new
{
template <class ContainerAllocator>
struct Flag_
{
  typedef Flag_<ContainerAllocator> Type;

  Flag_()
    : isMoving(0)  {
    }
  Flag_(const ContainerAllocator& _alloc)
    : isMoving(0)  {
  (void)_alloc;
    }



   typedef int32_t _isMoving_type;
  _isMoving_type isMoving;





  typedef boost::shared_ptr< ::yolo_new::Flag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_new::Flag_<ContainerAllocator> const> ConstPtr;

}; // struct Flag_

typedef ::yolo_new::Flag_<std::allocator<void> > Flag;

typedef boost::shared_ptr< ::yolo_new::Flag > FlagPtr;
typedef boost::shared_ptr< ::yolo_new::Flag const> FlagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_new::Flag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_new::Flag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_new::Flag_<ContainerAllocator1> & lhs, const ::yolo_new::Flag_<ContainerAllocator2> & rhs)
{
  return lhs.isMoving == rhs.isMoving;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_new::Flag_<ContainerAllocator1> & lhs, const ::yolo_new::Flag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_new

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_new::Flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_new::Flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_new::Flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_new::Flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_new::Flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_new::Flag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_new::Flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50d413790f6da206e162d072e2ef3ab7";
  }

  static const char* value(const ::yolo_new::Flag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50d413790f6da206ULL;
  static const uint64_t static_value2 = 0xe162d072e2ef3ab7ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_new::Flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_new/Flag";
  }

  static const char* value(const ::yolo_new::Flag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_new::Flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 isMoving\n"
;
  }

  static const char* value(const ::yolo_new::Flag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_new::Flag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isMoving);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Flag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_new::Flag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_new::Flag_<ContainerAllocator>& v)
  {
    s << indent << "isMoving: ";
    Printer<int32_t>::stream(s, indent + "  ", v.isMoving);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_NEW_MESSAGE_FLAG_H
