// Generated by gencpp from file yolo_new/Serial_RT.msg
// DO NOT EDIT!


#ifndef YOLO_NEW_MESSAGE_SERIAL_RT_H
#define YOLO_NEW_MESSAGE_SERIAL_RT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_new
{
template <class ContainerAllocator>
struct Serial_RT_
{
  typedef Serial_RT_<ContainerAllocator> Type;

  Serial_RT_()
    : sendClass()
    , count(0)  {
    }
  Serial_RT_(const ContainerAllocator& _alloc)
    : sendClass(_alloc)
    , count(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sendClass_type;
  _sendClass_type sendClass;

   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::yolo_new::Serial_RT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_new::Serial_RT_<ContainerAllocator> const> ConstPtr;

}; // struct Serial_RT_

typedef ::yolo_new::Serial_RT_<std::allocator<void> > Serial_RT;

typedef boost::shared_ptr< ::yolo_new::Serial_RT > Serial_RTPtr;
typedef boost::shared_ptr< ::yolo_new::Serial_RT const> Serial_RTConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_new::Serial_RT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_new::Serial_RT_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_new::Serial_RT_<ContainerAllocator1> & lhs, const ::yolo_new::Serial_RT_<ContainerAllocator2> & rhs)
{
  return lhs.sendClass == rhs.sendClass &&
    lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_new::Serial_RT_<ContainerAllocator1> & lhs, const ::yolo_new::Serial_RT_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_new

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_new::Serial_RT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_new::Serial_RT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_new::Serial_RT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_new::Serial_RT_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_new::Serial_RT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_new::Serial_RT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_new::Serial_RT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5e6d5a722f30a4aa4713722813adaed";
  }

  static const char* value(const ::yolo_new::Serial_RT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5e6d5a722f30a4aULL;
  static const uint64_t static_value2 = 0xa4713722813adaedULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_new::Serial_RT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_new/Serial_RT";
  }

  static const char* value(const ::yolo_new::Serial_RT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_new::Serial_RT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sendClass\n"
"int32 count\n"
;
  }

  static const char* value(const ::yolo_new::Serial_RT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_new::Serial_RT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sendClass);
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Serial_RT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_new::Serial_RT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_new::Serial_RT_<ContainerAllocator>& v)
  {
    s << indent << "sendClass: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sendClass);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_NEW_MESSAGE_SERIAL_RT_H
